-- ============================================================================
-- 003_jobs_audit_llm.sql — hàng đợi job + hai bảng ghi vết append-only
-- Không FK tới alerts/cases: `subject_id` là ĐA HÌNH (giữ cả alert_id text
-- lẫn case_id uuid), nên phải là text. Xem schema-notes.md · quyết định Q3.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- jobs — hàng đợi nằm TRONG PostgreSQL, không cần Redis (KT A2:62).
-- Vòng lặp worker: P4:42-50 `FOR UPDATE SKIP LOCKED`.
-- ---------------------------------------------------------------------------
CREATE TABLE jobs (
  job_id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- P4:42
  job_type      text        NOT NULL,                    -- P4:42
  subject_id    text        NOT NULL,                    -- P4:42
  status        text        NOT NULL DEFAULT 'pending',  -- P4:44
  scheduled_at  timestamptz NOT NULL DEFAULT now(),      -- P4:44 · backoff ghi vào đây
  locked_at     timestamptz,                             -- P4:49 · worker chết → nhặt lại
  attempts      integer     NOT NULL DEFAULT 0,          -- P4:49
  last_error    text,                                    -- P4:57
  created_at    timestamptz NOT NULL DEFAULT now(),

  -- Hai loại job, P5-1:38 "Số job | 1 | 2 (`enrich`, `triage`)"
  CONSTRAINT ck_jobs_job_type CHECK (job_type IN ('enrich','triage')),

  -- Trước 006: KHÔNG có CHECK trên `status`, vì đặc tả nêu 'pending' (P4:44), 'running'
  -- (P4:49), 'failed' (P4:68) nhưng KHÔNG nêu giá trị cho job chạy XONG.
  -- Bịa một giá trị rồi cưỡng chế nó là vượt quá đặc tả.
  -- Chốt S1 (25/08) đã thêm 'succeeded' → ck_jobs_status nằm ở migration 006.

  -- P4-7:58 · JOB_MAX_ATTEMPTS = 3
  CONSTRAINT ck_jobs_attempts_khong_am CHECK (attempts >= 0)
);

-- P4:42-47 · truy vấn nhặt job. Partial index: chỉ job đang chờ mới đáng đánh chỉ mục.
CREATE INDEX ix_jobs_pending
  ON jobs (scheduled_at)
  WHERE status = 'pending';

-- P4:70 · nhặt lại job của worker đã chết: locked_at < now() - JOB_LOCK_TIMEOUT_S
CREATE INDEX ix_jobs_running_locked
  ON jobs (locked_at)
  WHERE status = 'running';

-- ---------------------------------------------------------------------------
-- audit_events — append-only (KT A3:90). Không UPDATE, không DELETE.
-- Khóa chính KHÔNG có trong đặc tả — xem Cần bổ sung #2.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_events (
  audit_id    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type  text        NOT NULL,   -- P2:245 'alert.duplicate_merged', P6:106 'alert.acknowledged', …
  subject_id  text        NOT NULL,   -- alert_id (text) HOẶC case_id (uuid) — P7:325
  actor_id    uuid,                   -- P6:105 · NULL khi actor_role='system'
  actor_role  text        NOT NULL,   -- P2:246 'system', P5:143 'llm', P6:106 'analyst'
  payload     jsonb,                  -- P2:247
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ck_audit_actor_role CHECK (actor_role IN ('system','llm','analyst'))
);

-- Phép đo ③ (KT B7:387) JOIN llm_runs ↔ audit_events theo subject_id
CREATE INDEX ix_audit_subject ON audit_events (subject_id, created_at);
CREATE INDEX ix_audit_event_type ON audit_events (event_type, created_at);

-- ---------------------------------------------------------------------------
-- llm_runs — append-only. Cột nguyên văn P5:131-135 + P7:321-324.
-- `user_message` chứa TOÀN BỘ prompt đã gửi (P5:145) — đây là lý do enrichment
-- không cần bảng riêng (KT B2:219).
-- I4 (P7:429) · mỗi lần chạy ② ghi MỘT DÒNG MỚI, không ghi đè.
-- ---------------------------------------------------------------------------
CREATE TABLE llm_runs (
  run_id              uuid        PRIMARY KEY,   -- P5:131 · app cấp, không DEFAULT
  pipeline            text        NOT NULL,      -- P5:135 'triage' · P7:327 'investigate'
  subject_type        text        NOT NULL,      -- P5:135 'alert' · P7:327 'case'
  subject_id          text        NOT NULL,      -- alert_id HOẶC case_id
  system_prompt       text        NOT NULL,      -- P5:132
  user_message        text        NOT NULL,      -- P5:132 · nguyên văn prompt (T7)
  agent_trace         jsonb,                     -- P5:132
  result              jsonb,                     -- P5:132 · NULL khi model hỏng (T6)
  injection_findings  jsonb,                     -- P5:133
  citation_warnings   jsonb,                     -- P5:133
  input_tokens        integer,                   -- P5:134
  output_tokens       integer,                   -- P5:134
  latency_ms          integer,                   -- P5:134
  created_at          timestamptz NOT NULL DEFAULT now(),

  -- M-C · `pipeline` là TEXT, không phải số nguyên. P3:253 viết `pipeline = 1`
  -- là câu cũ; P5:175, P6:35, P7:241 đều dùng chuỗi. Xem schema-notes.md.
  CONSTRAINT ck_llm_runs_pipeline CHECK (pipeline IN ('triage','investigate')),
  CONSTRAINT ck_llm_runs_subject_type CHECK (subject_type IN ('alert','case')),

  -- Hai cặp phải khớp nhau: ① chạy trên alert, ② chạy trên case (P7:20)
  CONSTRAINT ck_llm_runs_pipeline_khop_subject CHECK (
    (pipeline = 'triage'      AND subject_type = 'alert')
    OR (pipeline = 'investigate' AND subject_type = 'case')
  ),

  -- P5-5 · suggested_action là TẬP ĐÓNG BA GIÁ TRỊ; giá trị lạ coi như hỏng.
  -- Cưỡng chế ngay trong DB thay vì tin vào tầng ứng dụng.
  CONSTRAINT ck_llm_runs_suggested_action CHECK (
    pipeline <> 'triage'
    OR result IS NULL
    OR result->>'suggested_action' IS NULL
    OR result->>'suggested_action' IN ('false_positive','needs_review','escalate')
  ),

  -- P7:273 · ② có giá trị thứ tư `need_more_data` mà ① không có
  CONSTRAINT ck_llm_runs_suggested_conclusion CHECK (
    pipeline <> 'investigate'
    OR result IS NULL
    OR result->>'suggested_conclusion' IS NULL
    OR result->>'suggested_conclusion' IN
       ('false_positive','policy_violation','confirmed_incident','need_more_data')
  )
);

-- P6:34-36 · LEFT JOIN hàng đợi Tier 1 lấy gợi ý ①
-- P7:241    · đọc lịch sử ② của một case
CREATE INDEX ix_llm_runs_subject ON llm_runs (subject_id, pipeline, created_at DESC);

INSERT INTO schema_migrations (version) VALUES ('003_jobs_audit_llm');

COMMIT;
