-- ============================================================================
-- 014_intake_cursor_heartbeat.sql — the intake ledger and the puller's state
--
-- Context pack §6.1 (three new v3 tables) and §5 (the flow that writes them):
--   intake            one row per document read from a manager, plus a receipt
--   source_cursor     where the next pull resumes from, per manager
--   source_heartbeat  when a manager was last heard from, and last heard with
--
-- Append-only enforcement on `intake` is NOT here. Migration 017 owns it and
-- applies it on top of this file (DEC-023 item 1): REVOKE UPDATE, DELETE,
-- TRUNCATE, then a column-level GRANT UPDATE (processed_at, outcome, error) for
-- the G12 completion write, then the pinning triggers. This file creates the
-- three tables with their constraints and nothing else — no GRANT, no REVOKE,
-- no trigger, no index beyond the ones the keys imply.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- intake — the ledger every alert enters through, from either intake path
-- (§5: the 60 s puller, and POST /webhook/alerts as the secondary path).
--
-- G9, as re-worded by DEC-023: `raw_text` is the received document unchanged —
-- the webhook body, the hit object's bytes sliced from the pull response, or
-- the archive line for a replay row — and `raw_payload` is derived from it and
-- may be normalised. Byte identity cannot hold on jsonb: measured on this
-- cluster, '{"b":1,"a":2,  "c":3}' comes back from jsonb as
-- '{"a": 2, "b": 1, "c": 3}' — keys reordered, whitespace collapsed. So the
-- received document lives in `text` (server_encoding is UTF8 and JSON text is
-- UTF-8 by RFC 8259, so text preserves every valid input byte and rejects
-- invalid UTF-8 loudly) and the jsonb is generated from it, never inserted.
-- The generated column doubles as the well-formedness check: 'not json' fails
-- with `invalid input syntax for type json`.
--
-- No foreign key to `alerts`, in either direction. §6.1 gives `alerts` no
-- `intake_id` and `intake` no `alert_id`; the link is carried by the
-- jobs('pipeline', intake_id) row. An FK here would extend a frozen contract.
-- ---------------------------------------------------------------------------
CREATE TABLE intake (
  intake_id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manager_id       text        NOT NULL,   -- §6.3 WAZUH_MANAGER_ID, e.g. 'IA1803'
  source_alert_id  text        NOT NULL,   -- the manager's own alert id, e.g. '1788340536.1509017'
  raw_text         text        NOT NULL,   -- G9: the received bytes, unchanged (DEC-023)
  raw_payload      jsonb       NOT NULL GENERATED ALWAYS AS (raw_text::jsonb) STORED,
  sort_key         bigint,                 -- indexer `sort`; computed for replay rows (DEC-019)
  via              text        NOT NULL,
  received_at      timestamptz NOT NULL DEFAULT now(),  -- §9: control time comes from the DB
  processed_at     timestamptz,            -- G12: this or `error`, within 60 s
  outcome          text,
  error            text,

  -- §5 · the puller overlaps its window by 60 s, so it re-reads rows it has
  -- already stored. This is what makes a double pull idempotent.
  CONSTRAINT uq_intake_manager_source UNIQUE (manager_id, source_alert_id),

  CONSTRAINT ck_intake_via     CHECK (via IN ('pull','webhook')),

  -- Both `outcome` and `processed_at` are nullable on purpose: a row is
  -- inserted the moment it is read and only later resolved. G12 is what forces
  -- a value within 60 s, and G12 is a health check in P5, not a DB constraint —
  -- so the CHECK has to admit NULL or it would reject every fresh row.
  CONSTRAINT ck_intake_outcome CHECK (outcome IS NULL
    OR outcome IN ('alert','duplicate','auto_closed','heartbeat','rejected'))
);

-- ---------------------------------------------------------------------------
-- source_cursor — the persistent `search_after` cursor, one row per manager.
-- Everything but the key is nullable: a manager is registered before its first
-- pull has produced anything to resume from, and `last_error` holds the last
-- failure without stopping the next attempt.
-- ---------------------------------------------------------------------------
CREATE TABLE source_cursor (
  manager_id   text PRIMARY KEY,
  last_sort    bigint,       -- the `sort` value of the last hit consumed
  last_pull_at timestamptz,
  last_error   text
);

-- ---------------------------------------------------------------------------
-- source_heartbeat — `last_seen_at` is when the manager answered at all,
-- `last_alert_at` is when it last answered with an alert. The gap between the
-- two is what heartbeat detection reads in P2; a quiet manager is not a dead
-- one (DEC-014: the median day is 592 alerts, but the distribution is spiky).
-- ---------------------------------------------------------------------------
CREATE TABLE source_heartbeat (
  manager_id    text PRIMARY KEY,
  last_seen_at  timestamptz,
  last_alert_at timestamptz
);

INSERT INTO schema_migrations (version) VALUES ('014_intake_cursor_heartbeat');

COMMIT;
