-- ============================================================================
-- 017_append_only_and_roles.sql — AI Support SOC
-- §6.1 "Append-only enforcement", as amended by DEC-023 and DEC-024(a).
-- Runs after 016, as the database owner. KHÔNG sửa 001-016: chúng đã áp.
--
-- `audit_events`, `llm_runs` and `intake` become append-only against TWO layers,
-- because neither one alone covers everyone who can reach the database:
--
--   Layer 1 — privileges. Binds the application role `app_rw`, and answers
--     before any trigger runs. It does NOT bind the owner, who is the grantor.
--   Layer 2 — triggers. Bind everyone the privilege layer does not, the owner
--     included. A row trigger does not fire on TRUNCATE (DEC-016, measured), so
--     each table also carries a BEFORE TRUNCATE ... FOR EACH STATEMENT trigger.
--
-- The one write that must survive both layers is G12's: every `intake` row gets
-- `processed_at` or `error` within 60 s, which is one UPDATE on a row that was
-- INSERTed on arrival. Layer 1 admits it as a column-level grant, layer 2 as the
-- only shape `intake_pin_receipt()` lets through.
--
-- `app_rw` is cluster-global, not per-database. This file creates it when it is
-- absent, so migrations 013-017 are one repeatable command on any cluster whose
-- migrator can create roles (DEC-024(a)). It is created NOLOGIN deliberately:
-- the role authenticates over TCP with a SCRAM password, a passwordless LOGIN
-- role cannot connect at all, and a password must never enter a migration on a
-- public remote (DEC-022). Granting LOGIN and a password stays a one-off
-- out-of-band step per cluster — HUONG-DAN-VAN-HANH.md §0. NOLOGIN is enough
-- here: every GRANT/REVOKE and both append-only layers bind a NOLOGIN role
-- exactly as they bind a LOGIN one.
--
-- `domain_rw` is a v1 role on the legacy `soc` database and holds nothing on
-- `soc_dev` (DEC-024(d)). This migration names `app_rw` only.
-- ============================================================================
BEGIN;

-- The role must exist before anything below can bind it. Create it when absent;
-- fail loudly, never silently, when this migrator is not allowed to — a REVOKE
-- that binds nothing is the one outcome that must not be reachable.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
    BEGIN
      CREATE ROLE app_rw NOLOGIN;
    EXCEPTION WHEN insufficient_privilege THEN
      RAISE EXCEPTION USING
        MESSAGE = 'migration 017: role app_rw does not exist and this migrator cannot create it',
        HINT    = 'one-off superuser step, see docs/plan/HUONG-DAN-VAN-HANH.md §0 "Prerequisites"';
    END;
  END IF;
END
$$;

-- Application privileges: an explicit list, so TRUNCATE is never granted.
-- `GRANT ALL PRIVILEGES` would carry TRUNCATE and quietly undo half of this file.
GRANT USAGE ON SCHEMA public TO app_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_rw;
-- v1 uses GENERATED BY DEFAULT AS IDENTITY, which needs no sequence grant; the
-- line above closes the gap if anyone ever adds a `serial`. The two lines below
-- cover tables created after 017, so P2 needs no grants migration of its own.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_rw;

-- Bookkeeping table is the migrator's alone.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON schema_migrations FROM app_rw, PUBLIC;

-- Layer 1 — privileges. Table-level REVOKE first: a table-level REVOKE also
-- removes column-level grants of the same kind, so the column GRANT must follow
-- it. Measured the other way round, has_column_privilege(...) came back false.
REVOKE UPDATE, DELETE, TRUNCATE ON audit_events, llm_runs, intake FROM app_rw, PUBLIC;
GRANT  UPDATE (processed_at, outcome, error) ON intake TO app_rw;   -- G12 completion write

-- Layer 2 — triggers, which also bind the owner.
CREATE FUNCTION raise_immutable() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  RAISE EXCEPTION 'append-only table: % is immutable', TG_TABLE_NAME;
END
$fn$;

-- `intake` is the one append-only table with a legitimate second write. Payload
-- columns never change; the three receipt columns may each be written once.
CREATE FUNCTION intake_pin_receipt() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.intake_id       IS DISTINCT FROM OLD.intake_id
  OR NEW.manager_id      IS DISTINCT FROM OLD.manager_id
  OR NEW.source_alert_id IS DISTINCT FROM OLD.source_alert_id
  OR NEW.raw_text        IS DISTINCT FROM OLD.raw_text
  OR NEW.sort_key        IS DISTINCT FROM OLD.sort_key
  OR NEW.via             IS DISTINCT FROM OLD.via
  OR NEW.received_at     IS DISTINCT FROM OLD.received_at THEN
    RAISE EXCEPTION 'append-only table: intake row % payload columns are immutable', OLD.intake_id;
  END IF;
  IF (OLD.processed_at IS NOT NULL AND NEW.processed_at IS DISTINCT FROM OLD.processed_at)
  OR (OLD.outcome      IS NOT NULL AND NEW.outcome      IS DISTINCT FROM OLD.outcome)
  OR (OLD.error        IS NOT NULL AND NEW.error        IS DISTINCT FROM OLD.error) THEN
    RAISE EXCEPTION 'append-only table: intake row % receipt columns are pinned once set', OLD.intake_id;
  END IF;
  RETURN NEW;
END
$fn$;

CREATE TRIGGER trg_audit_events_immutable   BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW       EXECUTE FUNCTION raise_immutable();
CREATE TRIGGER trg_llm_runs_immutable       BEFORE UPDATE OR DELETE ON llm_runs     FOR EACH ROW       EXECUTE FUNCTION raise_immutable();
CREATE TRIGGER trg_intake_pin_receipt       BEFORE UPDATE           ON intake       FOR EACH ROW       EXECUTE FUNCTION intake_pin_receipt();
CREATE TRIGGER trg_intake_immutable         BEFORE DELETE           ON intake       FOR EACH ROW       EXECUTE FUNCTION raise_immutable();
-- A row trigger does not fire on TRUNCATE (DEC-016, kept by DEC-020).
CREATE TRIGGER trg_audit_events_no_truncate BEFORE TRUNCATE ON audit_events FOR EACH STATEMENT EXECUTE FUNCTION raise_immutable();
CREATE TRIGGER trg_llm_runs_no_truncate     BEFORE TRUNCATE ON llm_runs     FOR EACH STATEMENT EXECUTE FUNCTION raise_immutable();
CREATE TRIGGER trg_intake_no_truncate       BEFORE TRUNCATE ON intake       FOR EACH STATEMENT EXECUTE FUNCTION raise_immutable();

INSERT INTO schema_migrations (version) VALUES ('017_append_only_and_roles');

COMMIT;
